// generated by `sqlx migrate build-script`
use std::process::Command;

fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs/tags");
    println!("cargo:rerun-if-changed=../.git/packed-refs");

    let version = resolve_version().unwrap_or_else(|| "0.0.0-dev".to_string());
    println!("cargo:rustc-env=BACKEND_APP_VERSION={version}");
}

fn resolve_version() -> Option<String> {
    let output = Command::new("git")
        .args(["tag", "--points-at", "HEAD"])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let tags = String::from_utf8(output.stdout).ok()?;

    tags.lines().find_map(normalize_tag_version)
}

fn normalize_tag_version(tag: &str) -> Option<String> {
    let raw = tag.trim();
    let stripped = raw.strip_prefix('v')?;

    if is_valid_semver(stripped) {
        return Some(stripped.to_string());
    }

    None
}

fn is_valid_semver(version: &str) -> bool {
    let (core_and_pre, build) = split_once(version, '+');
    let (core, pre) = split_once(core_and_pre, '-');

    if !is_valid_core(core) {
        return false;
    }

    if let Some(pre_release) = pre {
        if !is_valid_identifiers(pre_release) {
            return false;
        }
    }

    if let Some(build_metadata) = build {
        if !is_valid_identifiers(build_metadata) {
            return false;
        }
    }

    true
}

fn is_valid_core(core: &str) -> bool {
    let parts: Vec<&str> = core.split('.').collect();
    if parts.len() != 3 {
        return false;
    }

    parts.into_iter().all(|part| {
        !part.is_empty()
            && part.chars().all(|character| character.is_ascii_digit())
            && (part == "0" || !part.starts_with('0'))
    })
}

fn is_valid_identifiers(identifiers: &str) -> bool {
    identifiers.split('.').all(|identifier| {
        !identifier.is_empty()
            && identifier
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '-')
    })
}

fn split_once<'a>(value: &'a str, separator: char) -> (&'a str, Option<&'a str>) {
    if let Some((left, right)) = value.split_once(separator) {
        return (left, Some(right));
    }

    (value, None)
}
