// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Product = {
  id: bigint;
  barcode: string;
  expiration_date: string;
  created_at: string;
  client_id: string;
};
