// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Barcode = {
  id: bigint;
  code: string;
  url: string | null;
  creator: string | null;
  created_t: bigint | null;
  created_datetime: string | null;
  last_modified_t: bigint | null;
  last_modified_datetime: string | null;
  last_modified_by: string | null;
  last_updated_t: bigint | null;
  last_updated_datetime: string | null;
  product_name: string | null;
  abbreviated_product_name: string | null;
  generic_name: string | null;
  quantity: string | null;
  packaging: string | null;
  brands: string | null;
  categories: string | null;
  countries: string | null;
  countries_en: string | null;
  ingredients_text: string | null;
  nutriscore_score: number | null;
  nutriscore_grade: string | null;
  nova_group: number | null;
  image_url: string | null;
  image_small_url: string | null;
  last_image_t: bigint | null;
  last_image_datetime: string | null;
  main_category: string | null;
  main_category_en: string | null;
};
