// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProduct = {
  barcode: string;
  name: string;
  image: string | null;
  image_base64: string | null;
  expiration_date: string;
  client_id: string;
};
