// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateStock = {
  name: string;
  desired_quantity: number;
  current_quantity: number;
  unit: string | null;
  location: string | null;
  client_id: string;
};
