// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditProduct = {
  id: bigint;
  barcode: string;
  name: string;
  image: string | null;
  expiration_date: string;
  client_id: string;
};
