// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FreezeProduct = {
	product_id: bigint;
	client_id: string;
	total_portions: number;
	keep_in_fridge: number;
};
