// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductPrefill = {
  barcode: string;
  name: string | null;
  image: string | null;
  source: string;
};
