-- Add migration script here

CREATE TABLE barcode_database (
	id bigint GENERATED ALWAYS AS IDENTITY,
	code TEXT NOT NULL,
	url TEXT,
	creator TEXT,
	created_t BIGINT,
	created_datetime TIMESTAMPTZ,
	last_modified_t BIGINT,
	last_modified_datetime TIMESTAMPTZ,
	last_modified_by TEXT,
	last_updated_t BIGINT,
	last_updated_datetime TIMESTAMPTZ,
	product_name TEXT,
	abbreviated_product_name TEXT,
	generic_name TEXT,
	quantity TEXT,
	packaging TEXT,
	brands TEXT,
	categories TEXT,
	countries TEXT,
	countries_en TEXT,
	ingredients_text TEXT,
	nutriscore_score INTEGER,
	nutriscore_grade TEXT,
	nova_group INTEGER,
	image_url TEXT,
	image_small_url TEXT,
	last_image_t BIGINT,
	last_image_datetime TIMESTAMPTZ,
	main_category TEXT,
	main_category_en TEXT
);