GET http://localhost:3000/products HTTP/1.1

###

POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    "barcode": "0123456789124",
    "expiration_date": "2026-02-07",
    "client_id": "c36edaf3-4d57-47e0-a5fe-ca54d65ccec1"
}

###

DELETE http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
	"id": 1,
    "client_id": "c36edaf3-4d57-47e0-a5fe-ca54d65ccec1"
}