GET http://localhost:3000/products HTTP/1.1

###

GET http://localhost:3000/products?client_id=a3057b80-46d0-4013-9509-9eebd4a8ca2b HTTP/1.1

###

POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    "barcode": "5055950623132",
    "expiration_date": "2026-02-05",
    "client_id": "a3057b80-46d0-4013-9509-9eebd4a8ca2b"
}

###

DELETE http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
	"id": 8,
    "client_id": "a3057b80-46d0-4013-9509-9eebd4a8ca2b"
}

###
GET http://localhost:3000/barcodes/3242274030056 HTTP/1.1

###

GET http://localhost:3000/barcodes HTTP/1.1

###

GET http://localhost:3000/products/with-barcode?client_id=a3057b80-46d0-4013-9509-9eebd4a8ca2b HTTP/1.1