name: test-on-pr

on:
    push:
        branches: ["main"]
        paths:
            - "mobile/**"
            - ".github/workflows/tauri.yml"
    pull_request:
        branches: ["main"]
        paths:
            - "mobile/**"
            - ".github/workflows/tauri.yml"

jobs:
    check-mobile:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: mobile/src-tauri

            - name: Install system dependencies
              uses: awalsh128/cache-apt-pkgs-action@v1
              with:
                  packages: libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
                  version: 1

            - name: Install frontend dependencies
              working-directory: ./mobile
              run: bun install

            - name: Build frontend
              working-directory: ./mobile
              run: bun run build

            - name: Check Rust code
              working-directory: ./mobile/src-tauri
              run: cargo check --locked

    build-mobile:
        needs: check-mobile
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: ubuntu-22.04
                      mobile: android
                      rust-targets: aarch64-linux-android
                      args: ""
                    - platform: macos-latest
                      mobile: ios
                      rust-targets: aarch64-apple-ios,aarch64-apple-ios-sim
                      args: --target aarch64-apple-ios-sim

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Java
              if: matrix.mobile == 'android'
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "17"

            - name: Setup Android SDK
              if: matrix.mobile == 'android'
              uses: android-actions/setup-android@v3

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.rust-targets }}

            - name: Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: mobile/src-tauri

            - name: Install frontend dependencies
              working-directory: ./mobile
              run: bun install

            - name: Install system dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              uses: awalsh128/cache-apt-pkgs-action@v1
              with:
                  packages: libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
                  version: 1

            - name: Build mobile app
              uses: tauri-apps/tauri-action@v0.6.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  projectPath: ./mobile
                  tauriScript: bun tauri
                  mobile: ${{ matrix.mobile }}
                  args: ${{ matrix.args }}
